version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      NO_DOT_ENV: 1
      UVICORN_HOST: "0.0.0.0"
      UVICORN_PORT: 8000
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/word_db
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=word_db
