"""fix translation uniquness

Revision ID: 488a41e135e8
Revises: 69d607df9825
Create Date: 2023-10-28 20:15:52.188668

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "488a41e135e8"
down_revision = "69d607df9825"
branch_labels = None
depends_on = None


def upgrade():
    # Preprocess
    pre_upgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_translations_word", table_name="translations")
    op.create_index(
        op.f("ix_translations_word"), "translations", ["word"], unique=False
    )
    # ### end Alembic commands ###

    # Postprocess
    post_upgrade()


def downgrade():
    # Preprocess
    pre_downgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_translations_word"), table_name="translations")
    op.create_index("ix_translations_word", "translations", ["word"], unique=False)
    # ### end Alembic commands ###

    # Postprocess
    post_downgrade()


def pre_upgrade():
    # Processing before upgrading the schema
    pass


def post_upgrade():
    # Processing after upgrading the schema
    pass


def pre_downgrade():
    # Processing before downgrading the schema
    pass


def post_downgrade():
    # Processing after downgrading the schema
    pass
