"""update translation unique constraint

Revision ID: 69d607df9825
Revises: caf48c69f0c6
Create Date: 2023-10-27 18:50:57.152906

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "69d607df9825"
down_revision = "caf48c69f0c6"
branch_labels = None
depends_on = None


def upgrade():
    # Preprocess
    pre_upgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uc_word_source_lang_target_lang", "translations", type_="unique"
    )
    op.create_unique_constraint(
        "uc_word_target_lang", "translations", ["word", "target_lang"]
    )
    # ### end Alembic commands ###

    # Postprocess
    post_upgrade()


def downgrade():
    # Preprocess
    pre_downgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uc_word_target_lang", "translations", type_="unique")
    op.create_unique_constraint(
        "uc_word_source_lang_target_lang",
        "translations",
        ["word", "source_lang", "target_lang"],
    )
    # ### end Alembic commands ###

    # Postprocess
    post_downgrade()


def pre_upgrade():
    # Processing before upgrading the schema
    pass


def post_upgrade():
    # Processing after upgrading the schema
    pass


def pre_downgrade():
    # Processing before downgrading the schema
    pass


def post_downgrade():
    # Processing after downgrading the schema
    pass
